---
snapshot:
  name_template: '{{ incminor .Version }}-prerelease'

builds:
  - main: .
    binary: protoc-gen-go-hashpb
    id: "protoc-gen-go-hashpb"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/cerbos/protoc-gen-go-hashpb/internal/generator.Version={{.Version}}
dockers:
  - image_templates:
      - "plugins.buf.build/cerbos/protoc-gen-go-hashpb:v{{ .Version }}"
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
checksum:
  name_template: 'checksums.txt'
